version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: root-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - ollama

  db:
    image: postgres
    container_name: database-container
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=apihubDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - 8080:8080

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-container
    restart: unless-stopped
    ports:
      - "11434:11434"